### PR TITLE
🌲 Some improvements for huge tests

### PR DESCRIPTION
**Pull request by dmihalcik-virtru**
- Improves log statements to include time estimate
- Increases playwright timeouts to 15 minutes
- Deletes temp files after tests finish
- Reduce huge test file size from 8 to 5 GiB

### CODE REVIEW

**Comment by dmihalcik-virtru** [comment]
Sample run ongoing at https://github.com/opentdf/client-web/actions/runs/4758178311/jobs/8455961533

**Comment by dmihalcik-virtru** [comment]
Trying again with 5 GiB files and deleting the plain texts

https://github.com/opentdf/client-web/actions/runs/4758476023/jobs/8456651032

**Comment by dmihalcik-virtru** [comment]
another try

https://github.com/opentdf/client-web/actions/runs/4759431872

**Comment by dmihalcik-virtru** [comment]
Successful test (when running just huge, no retries, chromium only): https://github.com/opentdf/client-web/actions/runs/4763203741/jobs/8466414277

Time will tell if this is sufficient to avoid a lot of flakes. 

A single huge test takes about 50s on my m1 and about 4 minutes on a GitHub runner.

**Review by pflynn-virtru — APPROVED** [review]

**Pull request merged**
